"""Kerf-corrector calibration helpers: generates four physical test cuts --
a plain nominal-size square for finding a machine's basic kerf, and three
real-joint-shaped ladders (one fixed reference plus several swept-clearance
pieces, or paired-swept pieces where the joint kind has no fixed side) for
mortice+tenon, teeth, and slot. See docs/calibration-process.md for the
methodology this implements and docs/joint-types-and-settings.md for the
underlying physics.

Every ladder piece is generated by building a small hand-authored shape
with known vertex/winding structure, then running it through the real
correction engine (joints.analyze / joints.apply_manifest) rather than
reimplementing the shift math here -- the length/width asymmetry for a
windowed feature, and the closed-loop-vs-windowed sign flip for a void
feature, are both easy to get subtly wrong from a description alone (see
joints.py's apply_manifest and _extra_clearance_sign docstrings).

Two isolation patterns are used, matching which structural form each kind
actually needs (see joint-types-and-settings.md's "Structural forms"):

- WINDOWED features (tenon-as-attached, teeth, slot-as-notch) are each
  built as a single isolated element/subpath -- a small solid carrier
  panel with the feature on its boundary. Nesting depth is always 0 in
  isolation, which is exactly correct here: the carrier panel really is
  solid, unnested material, and a windowed feature's own shrink/grow
  direction comes from its LOCAL winding (shared with the carrier's own
  boundary), not from overall depth -- so isolation doesn't break it. See
  _correct_shape_d.
- CLOSED-LOOP voids (mortice; the only kind here that's ever closed-loop)
  are NOT safe to isolate the same way: a closed-loop void's shrink/grow
  direction is read from its own nesting depth, and an isolated closed
  loop always computes as depth 0 (same as solid material), which would
  make a lone mortice hole *grow* instead of shrink under kerf. It needs
  a real enclosing solid boundary in the same document so it's correctly
  computed at depth 1. See _correct_mortice_hole_d.

All settings this module's output feeds into: kerf_mm, mortice_clearance_mm
(always 0 here -- see calibration-process.md's "mortice stays fixed"
convention), tenon_clearance_mm, teeth_clearance_mm, slot_clearance_mm,
chamfer_mm.
"""

from __future__ import annotations

import io
from dataclasses import dataclass

from . import joints, svgio

_MIN_COUNT = 2
_MAX_COUNT = 12
_FONT_SIZE_MM = 3.2
_LABEL_GAP_MM = 6.0  # vertical room reserved below a row of pieces for its label
_TOP_MARGIN_MM = 10.0
_BOTTOM_MARGIN_MM = 6.0
_ROW_GAP_MM = 4.0  # vertical gap between two stacked rows within one piece/pair
_STROKE_WIDTH_MM = 0.001 * 25.4  # 0.001in hairline, in the document's own mm units
# Generous, fixed bounds for every isolated per-piece mini-document below --
# viewBox y-origin/height have no effect on correction (only the viewBox
# WIDTH vs. the mm width matters, for scale detection), so there's no need
# to compute tight bounds per shape; this comfortably contains any
# calibration-test-sized geometry regardless of protrusion direction.
_MINI_DOC_PAD_MM = 500.0


@dataclass
class KerfSquare:
    nominal_mm: float
    svg: str


def build_kerf_square(nominal_mm: float) -> KerfSquare:
    """A single solid square, drawn at exactly nominal_mm -- no kerf
    correction applied, since the whole point is to measure how much a
    known, uncorrected drawn size shrinks once actually cut."""
    if nominal_mm <= 0:
        raise ValueError("Square size must be positive.")

    x = _TOP_MARGIN_MM
    y = _TOP_MARGIN_MM
    rects = [(x, y, nominal_mm, nominal_mm)]
    labels = [(x + nominal_mm / 2, y + nominal_mm + _LABEL_GAP_MM - 1.5, f"{nominal_mm:g}mm square")]
    total_w = nominal_mm + 2 * _TOP_MARGIN_MM
    total_h = nominal_mm + _TOP_MARGIN_MM + _LABEL_GAP_MM + _BOTTOM_MARGIN_MM

    svg = _render_svg(total_w, total_h, rects, labels)
    return KerfSquare(nominal_mm=nominal_mm, svg=svg)


def clearances_mm(count: int, step_mm: float) -> list[float]:
    """Clearance values to test, starting at 0 (kerf-only correction, the
    tightest fit any ladder offers) and increasing by step_mm -- there's no
    reason to test a negative clearance, which would mean an intentionally
    tighter-than-kerf-alone interference fit."""
    return [round(i * step_mm, 4) for i in range(count)]


def _validate_ladder_params(nominal_mm: float, count: int, step_mm: float, engagement_depth_mm: float) -> None:
    if nominal_mm <= 0:
        raise ValueError("Nominal size must be positive.")
    if not (_MIN_COUNT <= count <= _MAX_COUNT):
        raise ValueError(f"Number of test pieces must be between {_MIN_COUNT} and {_MAX_COUNT}.")
    if step_mm <= 0:
        raise ValueError("Clearance step must be positive.")
    if engagement_depth_mm <= 0:
        raise ValueError("Engagement depth must be positive.")


def _check_largest_clearance_positive(nominal_mm: float, kerf_mm: float, largest_clearance: float) -> None:
    # Closed-form pre-check before paying for the real correction engine:
    # a solid feature's width axis (bounded by two independent walls)
    # shifts by the full kerf then shrinks by the full clearance -- see
    # apply_manifest's docstring. If that alone goes non-positive, every
    # other axis (which only ever gets a smaller, half-sized shift) will
    # too, so this one check catches it early with a clear message.
    if nominal_mm + kerf_mm - largest_clearance <= 0:
        raise ValueError(
            "The largest clearance value would shrink a piece to zero or negative "
            "width -- lower the step or the piece count."
        )


def _correct_shape_d(
    panel_w_mm: float,
    d: str,
    feature_entries: list[tuple[str, list[int]]],
    kerf_mm: float,
    **clearance_kwargs,
) -> str:
    """Run one isolated shape (a solid carrier panel, possibly with several
    windowed features on its boundary) through the real
    joints.apply_manifest and return the corrected 'd'. See this module's
    docstring for why isolation (always depth 0) is correct for every
    WINDOWED feature kind used here (tenon-as-attached, teeth, slot), and
    why it is NOT used for mortice."""
    svg_str = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{panel_w_mm:.4f}mm" height="{_MINI_DOC_PAD_MM:.4f}mm" '
        f'viewBox="0 {-_MINI_DOC_PAD_MM / 2:.4f} {panel_w_mm:.4f} {_MINI_DOC_PAD_MM:.4f}">'
        f'<path d="{d}" fill="none" stroke="black"/></svg>'
    )
    doc = svgio.load(io.BytesIO(svg_str.encode("utf-8")))
    elements = list(svgio.iter_shape_elements(doc.root))
    manifest = [
        {"element_index": 0, "subpath_index": 0, "kind": kind, "member_edges": edges}
        for kind, edges in feature_entries
    ]
    joints.apply_manifest(doc, elements, manifest, kerf_mm, **clearance_kwargs)
    return elements[0].get("d")


def _piece_group(x_mm: float, y_mm: float, d: str) -> str:
    return (
        f'<g transform="translate({x_mm:.4f},{y_mm:.4f})">'
        f'<path d="{d}" fill="none" stroke="black" stroke-width="{_STROKE_WIDTH_MM:.5f}"/></g>'
    )


def _label(x_mm: float, y_mm: float, text: str) -> str:
    return (
        f'<text x="{x_mm:.4f}" y="{y_mm:.4f}" font-size="{_FONT_SIZE_MM}" font-family="monospace" '
        f'fill="black" text-anchor="middle">{text}</text>'
    )


def _assemble_sheet(total_w_mm: float, total_h_mm: float, pieces: list[str], labels: list[str]) -> str:
    return "\n".join([
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{total_w_mm:.3f}mm" height="{total_h_mm:.3f}mm" '
        f'viewBox="0 0 {total_w_mm:.3f} {total_h_mm:.3f}">',
        f'<rect x="0" y="0" width="{total_w_mm:.3f}" height="{total_h_mm:.3f}" fill="none" stroke="black" '
        f'stroke-width="{_STROKE_WIDTH_MM:.5f}"/>',
        *pieces,
        *labels,
        "</svg>",
    ])


# ---------------------------------------------------------------------------
# Mortice + tenon: fixed mortice hole, swept (windowed, attached) tenons
# ---------------------------------------------------------------------------

@dataclass
class MorticeTenonLadder:
    nominal_mm: float
    kerf_mm: float
    clearances_mm: list[float]
    svg: str


def _panel_with_feature_d(
    panel_w_mm: float, panel_h_mm: float, feature_w_mm: float, feature_depth_mm: float, protrude: bool
) -> tuple[str, list[int]]:
    """Path 'd' for a solid rectangular panel spanning (0,0)-(panel_w,panel_h)
    with a single feature centered on its top edge (y=0): a protruding tab
    (protrude=True, tip above y=0 -- an attached tenon or a finger tooth) or
    an inward notch (protrude=False, tip below y=0, into the panel -- a
    slot). Vertex order/winding is the same shape any real uploaded panel
    with a windowed excursion on its boundary has, so joints.py's
    winding-derived outward-normal math treats it identically -- there's
    nothing special-cased for being a generated test shape.

    Returns (d, member_edges): member_edges are the vertex indices of the
    feature's own 3 walls (entry wall, cap, exit wall) -- the same shape
    an apply_manifest manifest entry expects.
    """
    cx = panel_w_mm / 2.0
    half = feature_w_mm / 2.0
    y_tip = -feature_depth_mm if protrude else feature_depth_mm
    pts = [
        (0.0, panel_h_mm),
        (0.0, 0.0),
        (cx - half, 0.0),
        (cx - half, y_tip),
        (cx + half, y_tip),
        (cx + half, 0.0),
        (panel_w_mm, 0.0),
        (panel_w_mm, panel_h_mm),
    ]
    d = "M " + " L ".join(f"{x:.4f},{y:.4f}" for x, y in pts) + " Z"
    return d, [3, 4, 5]


def _correct_mortice_hole_d(panel_w_mm: float, panel_h_mm: float, hole_w_mm: float, hole_h_mm: float,
                             kerf_mm: float) -> str:
    """A mortice hole, centered in its own solid panel -- unlike every
    other feature in this module, this one is NOT isolated as a lone
    element: mortice is the only kind here that's ever a genuinely CLOSED
    LOOP (see joint-types-and-settings.md), and a closed-loop void's
    shrink/grow direction is read from its own nesting depth, which an
    isolated single element always computes as 0 (same as solid material --
    wrong for a void). Putting a real enclosing boundary in the same
    document gets the hole correctly computed at depth 1. Always corrected
    with mortice_clearance_mm=0 -- see calibration-process.md's "mortice
    stays fixed" convention; only kerf ever moves this piece."""
    hx = (panel_w_mm - hole_w_mm) / 2.0
    hy = (panel_h_mm - hole_h_mm) / 2.0
    svg_str = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{panel_w_mm:.4f}mm" height="{panel_h_mm:.4f}mm" '
        f'viewBox="0 0 {panel_w_mm:.4f} {panel_h_mm:.4f}">'
        f'<rect x="0" y="0" width="{panel_w_mm:.4f}" height="{panel_h_mm:.4f}" fill="none" stroke="black"/>'
        f'<rect x="{hx:.4f}" y="{hy:.4f}" width="{hole_w_mm:.4f}" height="{hole_h_mm:.4f}" fill="none" stroke="black"/>'
        f'</svg>'
    )
    doc = svgio.load(io.BytesIO(svg_str.encode("utf-8")))
    elements = list(svgio.iter_shape_elements(doc.root))  # [outer panel, hole]
    manifest = [{"element_index": 1, "subpath_index": 0, "kind": "mortice", "member_edges": [1, 2, 3, 4]}]
    joints.apply_manifest(doc, elements, manifest, kerf_mm, mortice_clearance_mm=0.0)
    return elements[1].get("d")


def build_mortice_tenon_ladder(
    nominal_mm: float,
    kerf_mm: float,
    count: int = 5,
    step_mm: float = 0.05,
    engagement_depth_mm: float = 8.0,
) -> MorticeTenonLadder:
    """One fixed mortice socket (kerf-only, mortice_clearance_mm=0 always --
    the "mortice stays fixed" convention) plus `count` free-standing rail
    pieces, each with one tenon protruding from an end -- an actual
    attached tenon, not a free-floating tab, so its length axis correctly
    gets only half the kerf/clearance shift its width axis does (see this
    module's docstring). Swept across increasing tenon_clearance_mm.
    """
    _validate_ladder_params(nominal_mm, count, step_mm, engagement_depth_mm)
    clearances = clearances_mm(count, step_mm)
    _check_largest_clearance_positive(nominal_mm, kerf_mm, clearances[-1])

    margin_mm = max(nominal_mm * 0.75, 6.0)
    mortice_w = nominal_mm + 2 * margin_mm
    mortice_h = engagement_depth_mm + 2 * margin_mm
    rail_w = nominal_mm + 2 * margin_mm
    rail_h = 10.0

    gap_mm = max(nominal_mm * 1.5, 8.0)

    hole_d = _correct_mortice_hole_d(mortice_w, mortice_h, nominal_mm, engagement_depth_mm, kerf_mm)
    mortice_group = (
        f'<g transform="translate({gap_mm:.4f},{_TOP_MARGIN_MM:.4f})">'
        f'<rect x="0" y="0" width="{mortice_w:.4f}" height="{mortice_h:.4f}" fill="none" stroke="black" '
        f'stroke-width="{_STROKE_WIDTH_MM:.5f}"/>'
        f'<path d="{hole_d}" fill="none" stroke="black" stroke-width="{_STROKE_WIDTH_MM:.5f}"/></g>'
    )
    mortice_label = _label(gap_mm + mortice_w / 2, _TOP_MARGIN_MM + mortice_h + _LABEL_GAP_MM - 1.5,
                            f"mortice {nominal_mm:g}")

    tenon_baseline_y = _TOP_MARGIN_MM + mortice_h + _LABEL_GAP_MM + _ROW_GAP_MM + engagement_depth_mm + 6.0
    pieces = [mortice_group]
    labels = [mortice_label]
    x = gap_mm
    for c in clearances:
        d, edges = _panel_with_feature_d(rail_w, rail_h, nominal_mm, engagement_depth_mm, protrude=True)
        corrected = _correct_shape_d(rail_w, d, [("tenon", edges)], kerf_mm, tenon_clearance_mm=c)
        pieces.append(_piece_group(x, tenon_baseline_y, corrected))
        labels.append(_label(x + rail_w / 2, tenon_baseline_y + rail_h + _LABEL_GAP_MM - 1.5, f"+{c:g}"))
        x += rail_w + gap_mm

    total_w = max(gap_mm + mortice_w + gap_mm, x)
    total_h = tenon_baseline_y + rail_h + _LABEL_GAP_MM + _BOTTOM_MARGIN_MM

    svg = _assemble_sheet(total_w, total_h, pieces, labels)
    return MorticeTenonLadder(nominal_mm=nominal_mm, kerf_mm=kerf_mm, clearances_mm=clearances, svg=svg)


# ---------------------------------------------------------------------------
# Teeth: an actual multi-tooth finger-joint comb, both mating combs swept
# together (both get classified `teeth` in real use -- no fixed side)
# ---------------------------------------------------------------------------

@dataclass
class TeethLadder:
    nominal_mm: float
    kerf_mm: float
    teeth_per_comb: int
    clearances_mm: list[float]
    svg: str


def _comb_path_d(
    pattern: list[bool], finger_width_mm: float, panel_h_mm: float, depth_mm: float
) -> tuple[str, float, list[list[int]]]:
    """Path 'd' for a solid rectangular panel with a row of alternating
    teeth (True) and flush gaps (False) along its top edge, one
    finger_width_mm-wide segment per pattern entry -- an actual finger-joint
    comb, edge to edge, not one isolated tooth centered in a margin.

    Returns (d, panel_w_mm, tooth_member_edges): tooth_member_edges has one
    [left, cap, right] vertex-index triple per True entry, in pattern
    order, each ready to become its own manifest entry (kind="teeth"), all
    passed to the SAME apply_manifest call so they're corrected together.

    Known limitation: a MIDDLE gap (bounded by two teeth' facing walls,
    both independently corrected) correctly shrinks by the full kerf, so it
    grows back to true nominal width once actually cut -- verified in
    tests. But whichever pattern starts and/or ends with a gap (not a
    tooth) has an END gap bounded on one side by the panel's own plain
    carrier edge instead of a second tooth wall. That edge isn't part of
    any feature here, and giving it a generic "grow the panel outward"
    kerf correction doesn't fix this -- it just translates that whole gap
    sideways without changing its width, since a uniform shift of both
    endpoints in the same direction is a translation, not a width change.
    A true fix needs the panel's edge-adjacent wall to behave like a
    tooth's facing wall would (moving INTO the gap, not outward), which
    isn't a "plain edge" concept and isn't implemented. Net effect: the
    very first/last tooth-to-gap pairing across two mating combs is
    slightly looser than the interior ones -- roughly half the kerf's
    worth of extra slop, well under typical hand-fit-test perceptibility,
    and irrelevant to a real 3D box-joint corner (where a third panel, not
    this comb's own edge, fills that position). Judge overall fit from the
    interior teeth, not the very ends.
    """
    panel_w_mm = len(pattern) * finger_width_mm
    pts: list[tuple[float, float]] = [(0.0, panel_h_mm), (0.0, 0.0)]
    tooth_edges: list[list[int]] = []
    for i, is_tooth in enumerate(pattern):
        x1 = (i + 1) * finger_width_mm
        if is_tooth:
            x0 = i * finger_width_mm
            pts.append((x0, -depth_mm))
            left = len(pts) - 1
            pts.append((x1, -depth_mm))
            cap = len(pts) - 1
            pts.append((x1, 0.0))
            right = len(pts) - 1
            tooth_edges.append([left, cap, right])
        else:
            pts.append((x1, 0.0))
    pts.append((panel_w_mm, panel_h_mm))
    d = "M " + " L ".join(f"{x:.4f},{y:.4f}" for x, y in pts) + " Z"
    return d, panel_w_mm, tooth_edges


def _comb_patterns(teeth_per_comb: int) -> tuple[list[bool], list[bool]]:
    """Two complementary alternating patterns of the same length, each
    starting/ending on its own kind -- comb A starts/ends with a tooth
    (teeth_per_comb teeth), comb B starts/ends with a gap
    (teeth_per_comb - 1 teeth) -- so when brought together, A's teeth align
    with B's gaps and vice versa across the full width, the same layout a
    real finger-jointed box corner uses."""
    pattern_a = [i % 2 == 0 for i in range(2 * teeth_per_comb - 1)]
    pattern_b = [not is_tooth for is_tooth in pattern_a]
    return pattern_a, pattern_b


def build_teeth_ladder(
    nominal_mm: float,
    kerf_mm: float,
    count: int = 5,
    step_mm: float = 0.05,
    teeth_per_comb: int = 3,
    engagement_depth_mm: float = 8.0,
) -> TeethLadder:
    """`count` pairs of complementary finger-joint combs -- an actual
    multi-tooth interlocking pattern, not one tooth against a plain notch --
    both combs in a pair corrected with the SAME swept teeth_clearance_mm,
    since a real finger joint's teeth on both mating panels are normally
    both classified `teeth` (there's no fixed/swept asymmetry the way
    mortice/tenon has -- see calibration-process.md)."""
    _validate_ladder_params(nominal_mm, count, step_mm, engagement_depth_mm)
    if teeth_per_comb < 2:
        raise ValueError("Need at least 2 teeth per comb for a real interlocking pattern.")
    clearances = clearances_mm(count, step_mm)
    _check_largest_clearance_positive(nominal_mm, kerf_mm, clearances[-1])

    pattern_a, pattern_b = _comb_patterns(teeth_per_comb)
    carrier_h = 10.0
    gap_mm = max(nominal_mm * 1.5, 8.0)
    baseline_y = engagement_depth_mm + 6.0

    pieces: list[str] = []
    labels: list[str] = []
    x = gap_mm
    comb_w = 0.0
    for c in clearances:
        d_a, comb_w, edges_a = _comb_path_d(pattern_a, nominal_mm, carrier_h, engagement_depth_mm)
        corrected_a = _correct_shape_d(comb_w, d_a, [("teeth", e) for e in edges_a], kerf_mm, teeth_clearance_mm=c)
        d_b, _, edges_b = _comb_path_d(pattern_b, nominal_mm, carrier_h, engagement_depth_mm)
        corrected_b = _correct_shape_d(comb_w, d_b, [("teeth", e) for e in edges_b], kerf_mm, teeth_clearance_mm=c)

        pieces.append(_piece_group(x, baseline_y, corrected_a))
        pieces.append(_piece_group(x, baseline_y + carrier_h + _ROW_GAP_MM, corrected_b))
        labels.append(_label(x + comb_w / 2, baseline_y + 2 * carrier_h + _ROW_GAP_MM + _LABEL_GAP_MM - 1.5,
                              f"+{c:g}"))
        x += comb_w + gap_mm

    total_w = x
    total_h = baseline_y + 2 * carrier_h + _ROW_GAP_MM + _LABEL_GAP_MM + _BOTTOM_MARGIN_MM

    svg = _assemble_sheet(total_w, total_h, pieces, labels)
    return TeethLadder(nominal_mm=nominal_mm, kerf_mm=kerf_mm, teeth_per_comb=teeth_per_comb,
                        clearances_mm=clearances, svg=svg)


# ---------------------------------------------------------------------------
# Slot: two mating notches (a cross-lap/halving-joint style pair), both
# swept together (both sides share ONE clearance value -- no fixed side)
# ---------------------------------------------------------------------------

@dataclass
class SlotLadder:
    nominal_mm: float
    kerf_mm: float
    clearances_mm: list[float]
    svg: str


def build_slot_ladder(
    nominal_mm: float,
    kerf_mm: float,
    count: int = 5,
    step_mm: float = 0.05,
    engagement_depth_mm: float = 8.0,
) -> SlotLadder:
    """`count` pairs of notched panels -- a cross-lap/halving-joint style
    slot, where both mating pieces are voids that interlock where their
    notches overlap. Both notches in a pair corrected with the SAME swept
    slot_clearance_mm, matching the tool's own rule that both sides of a
    slot joint share one clearance value, not independent ones."""
    _validate_ladder_params(nominal_mm, count, step_mm, engagement_depth_mm)
    clearances = clearances_mm(count, step_mm)
    _check_largest_clearance_positive(nominal_mm, kerf_mm, clearances[-1])

    margin_mm = max(nominal_mm * 0.75, 6.0)
    panel_w = nominal_mm + 2 * margin_mm
    panel_h = 10.0
    gap_mm = max(nominal_mm * 1.5, 8.0)
    baseline_y = _TOP_MARGIN_MM

    pieces: list[str] = []
    labels: list[str] = []
    x = gap_mm
    for c in clearances:
        d_a, edges_a = _panel_with_feature_d(panel_w, panel_h, nominal_mm, engagement_depth_mm, protrude=False)
        corrected_a = _correct_shape_d(panel_w, d_a, [("slot", edges_a)], kerf_mm, slot_clearance_mm=c)
        d_b, edges_b = _panel_with_feature_d(panel_w, panel_h, nominal_mm, engagement_depth_mm, protrude=False)
        corrected_b = _correct_shape_d(panel_w, d_b, [("slot", edges_b)], kerf_mm, slot_clearance_mm=c)

        pieces.append(_piece_group(x, baseline_y, corrected_a))
        pieces.append(_piece_group(x, baseline_y + panel_h + _ROW_GAP_MM, corrected_b))
        labels.append(_label(x + panel_w / 2, baseline_y + 2 * panel_h + _ROW_GAP_MM + _LABEL_GAP_MM - 1.5,
                              f"+{c:g}"))
        x += panel_w + gap_mm

    total_w = x
    total_h = baseline_y + 2 * panel_h + _ROW_GAP_MM + _LABEL_GAP_MM + _BOTTOM_MARGIN_MM

    svg = _assemble_sheet(total_w, total_h, pieces, labels)
    return SlotLadder(nominal_mm=nominal_mm, kerf_mm=kerf_mm, clearances_mm=clearances, svg=svg)


def _render_svg(
    width_mm: float,
    height_mm: float,
    rects: list[tuple[float, float, float, float]],
    labels: list[tuple[float, float, str]],
) -> str:
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width_mm:.3f}mm" height="{height_mm:.3f}mm" '
        f'viewBox="0 0 {width_mm:.3f} {height_mm:.3f}">',
        f'<rect x="0" y="0" width="{width_mm:.3f}" height="{height_mm:.3f}" fill="none" stroke="black" stroke-width="{_STROKE_WIDTH_MM:.5f}"/>',
    ]
    for x, y, w, h in rects:
        parts.append(
            f'<rect x="{x:.4f}" y="{y:.4f}" width="{w:.4f}" height="{h:.4f}" fill="none" stroke="black" stroke-width="{_STROKE_WIDTH_MM:.5f}"/>'
        )
    for x, y, text in labels:
        parts.append(
            f'<text x="{x:.4f}" y="{y:.4f}" font-size="{_FONT_SIZE_MM}" font-family="monospace" '
            f'fill="black" text-anchor="middle">{text}</text>'
        )
    parts.append("</svg>")
    return "\n".join(parts)
